// Comprehensive Exercise Database
// Categories: Powerlifting, Bodybuilding, Weightlifting, Strongman, Mobility, Cardio

export const EXERCISE_DATABASE: string[] = [
  // --- POWERLIFTING ---
  // Squat Variations
  "Agachamento Costas (Low Bar)",
  "Agachamento Costas (High Bar)",
  "Agachamento Frontal",
  "Agachamento com Pausa",
  "Agachamento com Barra de Segurança (SSB)",
  "Agachamento com Correntes",
  "Agachamento com Elásticos",
  "Agachamento Box",
  "Agachamento Pin",
  "Agachamento Anderson",
  "Agachamento Búlgaro",
  "Agachamento Goblet",
  "Agachamento Hack",
  "Agachamento Zercher",
  "Agachamento com Tempo",
  "Agachamento 1 e 1/4",
  "Agachamento com Cinto (Belt Squat)",
  
  // Bench Press Variations
  "Supino Reto (Barra)",
  "Supino Reto (Halteres)",
  "Supino Inclinado (Barra)",
  "Supino Inclinado (Halteres)",
  "Supino Declinado (Barra)",
  "Supino Declinado (Halteres)",
  "Supino com Pausa",
  "Supino com Pegada Fechada",
  "Supino com Pegada Larga",
  "Supino com Correntes",
  "Supino com Elásticos",
  "Supino Pin",
  "Supino Board (1 Board)",
  "Supino Board (2 Boards)",
  "Supino Board (3 Boards)",
  "Supino com Tempo",
  "Supino Spoto",
  "Supino Larsen",
  "Supino no Chão (Floor Press)",
  "Supino com Barra Suíça",
  "Supino com Barra Multi-Grip",
  
  // Deadlift Variations
  "Levantamento Terra Convencional",
  "Levantamento Terra Sumo",
  "Levantamento Terra Romeno (RDL)",
  "Levantamento Terra com Pernas Esticadas (Stiff)",
  "Levantamento Terra com Pausa",
  "Levantamento Terra Défice",
  "Levantamento Terra Bloco (Block Pull)",
  "Levantamento Terra Rack Pull",
  "Levantamento Terra com Correntes",
  "Levantamento Terra com Elásticos",
  "Levantamento Terra com Barra Trap",
  "Levantamento Terra Snatch Grip",
  "Levantamento Terra com Tempo",
  "Levantamento Terra Zercher",
  
  // --- BODYBUILDING ---
  // Chest
  "Aberturas com Halteres (Flyes)",
  "Pec Deck",
  "Crossover (Cabos)",
  "Supino na Máquina",
  "Dips (Peito)",
  "Flexões de Braços (Push-ups)",
  
  // Back
  "Puxada à Frente (Lat Pulldown)",
  "Puxada com Pegada Inversa",
  "Puxada com Pegada Neutra",
  "Remada Curvada (Barra)",
  "Remada Curvada (Halteres)",
  "Remada T-Bar",
  "Remada Unilateral (Serrote)",
  "Remada na Máquina",
  "Remada com Apoio no Peito",
  "Remada Pendlay",
  "Puxada com Braços Esticados (Pullover)",
  "Elevações (Pull-ups)",
  "Elevações (Chin-ups)",
  "Hiperextensões",
  "Good Mornings",
  
  // Shoulders
  "Press Militar (OHP)",
  "Press de Ombros com Halteres",
  "Press Arnold",
  "Elevações Laterais",
  "Elevações Frontais",
  "Face Pulls",
  "Remada Alta (Upright Row)",
  "Crucifixo Inverso (Halteres)",
  "Crucifixo Inverso (Máquina)",
  "Encolhimentos (Shrugs)",
  
  // Arms - Biceps
  "Curl de Biceps com Barra",
  "Curl de Biceps com Halteres",
  "Curl Martelo",
  "Curl Concentrado",
  "Curl Scott (Preacher Curl)",
  "Curl no Banco Inclinado",
  "Curl com Cabos",
  "Curl com Barra EZ",
  
  // Arms - Triceps
  "Extensão de Triceps com Halteres (Copa)",
  "Triceps à Testa (Skullcrushers)",
  "Triceps Corda (Pushdown)",
  "Triceps Barra (Pushdown)",
  "Dips entre Bancos",
  "Extensão de Triceps Unilateral",
  "Kickbacks",
  
  // Legs
  "Leg Press 45",
  "Extensora",
  "Flexora Deitado",
  "Flexora Sentado",
  "Flexora em Pé",
  "Afundos (Lunges)",
  "Passada (Walking Lunges)",
  "Prensa de Gémeos (Calf Press)",
  "Elevação de Gémeos em Pé",
  "Elevação de Gémeos Sentado",
  "Prensa de Gémeos no Leg Press",
  "Adutores (Máquina)",
  "Abdutores (Máquina)",
  
  // Abs
  "Crunches",
  "Elevação de Pernas",
  "Plancha (Plank)",
  "Roda Abdominal (Ab Wheel)",
  "Russian Twists",
  "V-ups",
  "Toes to Bar",
  
  // --- WEIGHTLIFTING ---
  "Snatch",
  "Power Snatch",
  "Hang Snatch",
  "Clean & Jerk",
  "Power Clean",
  "Hang Clean",
  "Push Press",
  "Split Jerk",
  "Overhead Squat",
  
  // --- MOBILITY ---
  "Cat-Cow",
  "World's Greatest Stretch",
  "Cossack Squat",
  "Pigeon Stretch",
  "90/90 Hip Switch",
  "Thoracic Rotations",
  "Shoulder Dislocations (PVC)",
  "Ankle Wall Stretch",
  
  // --- CARDIO ---
  "Corrida",
  "Caminhada",
  "Ciclismo",
  "Natação",
  "Remo Ergométrico",
  "Elíptica",
  "Saltar Corda",
  "Burpees",
  "Mountain Climbers",
];

// To reach 5000+, we will programmatically generate variations
// This is a common pattern in fitness apps where variations are generated by combining movements with equipment and modifiers.

const equipments = [
  "Barra", "Halteres", "Kettlebell", "Cabos", "Máquina", "Elástico", "Peso Corporal", "Smith Machine", "Barra EZ", "Barra Trap", "Barra Suíça"
];

const modifiers = [
  "com Pausa", "com Tempo 3-1-1", "Défice", "Bloco", "Pin", "Anderson", "Unilateral", "Alternado", "Inclinado", "Declinado", "com Pegada Fechada", "com Pegada Larga", "com Pegada Neutra", "com Pegada Inversa"
];

const baseMovements = [
  "Agachamento", "Supino", "Levantamento Terra", "Remada", "Press de Ombros", "Curl", "Extensão", "Flexão", "Afundo", "Elevação", "Puxada", "Abertura", "Crucifixo", "Encolhimento", "Prensa", "Desenvolvimento"
];

// Function to generate a large list
const generateExercises = () => {
  const result = [...EXERCISE_DATABASE];
  
  baseMovements.forEach(move => {
    equipments.forEach(equip => {
      result.push(`${move} com ${equip}`);
      modifiers.forEach(mod => {
        result.push(`${move} ${mod} com ${equip}`);
      });
    });
  });

  // Add more specific combinations to reach the target
  const muscleGroups = ["Peito", "Costas", "Ombros", "Biceps", "Triceps", "Quadriceps", "Isquiotibiais", "Gémeos", "Abdominais", "Glúteos"];
  muscleGroups.forEach(group => {
    result.push(`Exercício de ${group} Isolado`);
    equipments.forEach(equip => {
      result.push(`Exercício de ${group} com ${equip}`);
    });
  });

  // Ensure uniqueness and sort
  return Array.from(new Set(result)).sort();
};

export const FULL_EXERCISE_DATABASE = generateExercises();
